url: 

gems:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag

kramdown:
  input: GFM

future: false
paginate: 5
paginate_path: "/posts/page:num/"

title: Nadine Randel
description: 
author: Nadine Randel
email: nadine.randel81@gmail.com
phone: 

# For use with [jekyll-seo-tag](https://github.com/jekyll/jekyll-seo-tag)
social:
  type: person
  name: Nadine Randel
  links:
    - https://twitter.com/nadinerandel 
    - https://github.com/nrandel


twitter:
  username: NadineRandel
github:
  username: nrandel
